base_url = "https://nnix.com"
title = "nnix.com"
description = "novo nilbud by swamplight: coal’s short but we got plenty of bog in the yard"
compile_sass = false
minify_html = false
default_language = "en"

taxonomies = [
	{ name = "recommender" },
	{ name = "authorname" },
	{ name = "pubyear" },
	{ name = "rating" },
	{ name = "readstate" },
	{ name = "foodcategory" }
]

[slugify]
paths = "on"
anchors = "on"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[link_checker]
internal_level = "warn"

[extra]
author = "David Emerson"
default_theme = "light"
twitter_card = true
epoch = "PLACEHOLDER"

# Site sections configuration
[extra.sections]
projects = { title = "projects", description = "Things I've built and made" }
reading = { title = "reading", description = "Books I've read and want to read" }
food = { title = "food", description = "Recipes and cooking experiments" }

# Food categories for cleaner template logic
[extra.food_categories]
bread-pastry = "bread & pastry"
desserts-snacks = "desserts & snacks"
dips-spreads = "dips & spreads"
drinks = "drinks"
main = "main dishes"