Port = 1965
Hostname = "nnix.com"
CertPath = "/web/certs/nnix.com.pem"
KeyPath = "/web/certs/nnix.com.key"
DocBase = "/web/nnix.com/capsule/"
#HomeDocBase = "users"
GeminiExt = "gmi"
DefaultLang = "en"
#AccessLog = "/var/log/molly/access.log"
#ErrorLog = "/var/log/molly/error.log"
#ReadMollyFiles = true
#
## Directory listing
#
DirectorySort = "Time"
#DirectoryReverse = true
DirectoryTitles = true
#
## Dynamic content
#
#[MimeOverrides]
#"atom.xml$" = "application/atom+xml"
#"rss.xml$" = "application/rss+xml"
#
## Redirects
#
#[TempRedirects]
#"/old/path/file.ext" = "/new/path/file.ext"
#[PermRedirects]
#"/old/path/file.ext" = "/new/path/file.ext"