# remember to add a space after each line of the server_name except before the semicolon!

worker_processes  1;

events {
       worker_connections  1024;
}
http {
       server_names_hash_bucket_size  128;
       include       mime.types;
       default_type  application/octet-stream;
       sendfile        on;
       keepalive_timeout  65;
server {
       server_name   nnix.com 
                     www.nnix.info 
                     nnix.info 
                     www.nnix.link 
                     nnix.link 
                     www.nnix.me 
                     nnix.me 
                     www.nnix.org 
                     nnix.org
                     ;
       return 301 https://www.nnix.com$request_uri;
       }
server {
       server_name   www.refmark.com 
                     www.refmark.co 
                     refmark.co 
                     www.refmark.org 
                     refmark.org 
                     www.refmark.net 
                     refmark.net
                     ;
       return 301 https://refmark.com$request_uri;
       }
server {
       server_name   www.davidemerson.com 
                     www.davidemerson.info 
                     davidemerson.info 
                     www.davidemerson.me 
                     davidemerson.me 
                     www.davidemerson.net 
                     davidemerson.net 
                     www.davidemerson.org 
                     davidemerson.org 
                     www.emerson.farm 
                     emerson.farm
                     ;
       return 301 https://davidemerson.com$request_uri;
       }
server {
       server_name   www.rexwilhelmina.com 
                     rexwilhelmina.com
                     ;
       return 301 https://rex.ax$request_uri;
       }
server {
       server_name   www.carrienieman.com 
                     carrienieman.com
                     www.carrienieman.info
                     carrienieman.info
                     www.carrienieman.net
                     carrienieman.net
                     www.carrienieman.org
                     carrienieman.org
                     www.hearinghealth.org
                     hearinghealth.org
                     baltimorehears.org
                     www.baltimorehears.org
                     baltimorehears.com
                     www.baltimorehears.com
                     baltimorehears.net
                     www.baltimorehears.net
                     ;
       return 301 https://cln.ax$request_uri;
       }
server {
       if ($host = nnix.com) 
              {
              return 301 https://$host$request_uri;
              }
       }
}