name: Build and Publish to AWS

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Zola Version
        id: zola_version
        run: |
          LATEST_ZOLA=$(curl -s https://api.github.com/repos/getzola/zola/releases/latest | jq -r .tag_name)
          echo "LATEST_ZOLA=${LATEST_ZOLA}" >> $GITHUB_ENV

      - name: Cache Zola Binary
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/zola
          key: zola-${{ env.LATEST_ZOLA }}-${{ runner.os }}

      - name: Install Latest Zola (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/${LATEST_ZOLA}/zola-${LATEST_ZOLA#v}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          mkdir -p ~/.cargo/bin
          mv zola ~/.cargo/bin/

      - name: Generate Current Unix Epoch
        id: get_epoch
        run: echo "epoch=$(date +%s)" >> $GITHUB_ENV

      - name: Inject Unix Epoch into config.toml
        run: |
          sed -i "s/PLACEHOLDER/$epoch/" config.toml

      - name: Build Zola Site
        run: ~/.cargo/bin/zola build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync public/ s3://nnix.com \
            --region us-east-1 \
            --delete \
            --cache-control max-age=86400 \
            --exclude ".DS_Store" \
            --exclude "*.tmp" \
            --exclude "debug/*"

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E4DE96M2EUA2N \
            --paths "/*"
