name: Build and Publish to AWS

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zola
        run: |
          curl -fSL https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
          mkdir -p ~/.cargo/bin
          mv zola ~/.cargo/bin/
          zola --version

      - name: Generate Current Unix Epoch
        id: get_epoch
        run: echo "epoch=$(date +%s)" >> $GITHUB_ENV

      - name: Inject Unix Epoch into config.toml
        run: |
          sed -i "s/PLACEHOLDER/$epoch/" config.toml

      - name: Build Zola Site
        run: ~/.cargo/bin/zola build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync public/ s3://nnix.com \
            --region us-east-1 \
            --delete \
            --cache-control max-age=86400 \
            --exclude ".DS_Store" \
            --exclude "*.tmp" \
            --exclude "debug/*" \
            --exact-timestamps

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E4DE96M2EUA2N \
            --paths "/*"
